Implemented step 1 and 2 for WoT. Still need to notify the POR subjec…
UCLA-IRL/ndnts-aux pull request #2
Opened 2024-02-20 04:28 UTC by ykocaogullar

Implemented following functionalities:

- Fetch stranger certificate by keylocator
- Request POR certificate issued by every other known (authenticated) user
  - If my cert store has N other users, send N interests for each
  - If not getting at least one POR, abort (treat as data verification failure)
- Cross-sign stranger public key as POR certificate
- Putting POR certificate into cert store
- POR subject serves all POR it received

Missing functionality: Notify the POR subject a new POR is generated, let it fetch by name

2024-02-20 10:31 UTC, zjkmxy commented
Hello. Please run `pnpm format`, `pnpm lint` and `pnpm test` locally and fix the errors.

2024-02-29 23:45 UTC, zjkmxy commented
How is your progress on this?

2024-03-02 21:51 UTC, ykocaogullar commented
> How is your progress on this?

I'll fix these before the end of the weekend.

2024-03-29 22:40 UTC, zjkmxy requested changes

2024-03-29 22:40 UTC, zjkmxy commented on src/security/cert-storage.ts
> +      }
First, I don't think this is the correct behavior. I think `<Tb keyid>` is a **single** component containing the encoded name. Please confirm with @tianyuan129 .
If this behavior is correct, you can still get rid of the loop. See [Name.append](https://ndnts-docs.ndn.today/typedoc/classes/_ndn_packet.name-1#append)

2024-03-29 22:40 UTC, zjkmxy commented on src/security/cert-storage.ts
> +        false,
This means PoR can be recursively signed by other unknown certifcates. Please check if the behavior if desired.

2024-03-29 22:40 UTC, zjkmxy commented on src/security/cert-storage.ts
> +    }
This reads as "a PoR cannot be generated without an existing one".
Then, how can the first PoR be generated?

2024-03-29 22:40 UTC, zjkmxy commented on src/security/cert-storage.ts
> +    const certificate: Certificate | undefined = await this.getCertificate(new Name(strangerKeyname), false);
Do you want to fetch a certificate when generating PoR?

2024-03-29 22:40 UTC, zjkmxy commented on src/security/cert-storage.ts
> +    });
Why a PoR is self-signed?

2024-04-27 03:43 UTC, closed without merging